name: Rust Build and Release (Windows)

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: version
        run: echo "::set-output name=version::$((Get-Content -Path .\Cargo.toml | Select-Object -Index 2) -replace '[^0-9.]')"
        id: version

      - name: output version
        run: echo "${{ steps.version.outputs.version }}"
