name: Rust Build and Release (Windows)

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: version
        run: echo "0.9.1" >> $GITHUB_OUTPUT
        id: version

      - name: Output Version
        run: echo ${{ steps.version.outputs.version }}
