name: Rust Build and Release (Windows)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable-msvc

      - name: Prerequisites gvsbuild
        run: |
          winget install --id Git.Git -e --source winget
          winget install --id MSYS2.MSYS2 -e --source winget
          winget install Microsoft.VisualStudio.2022.BuildTools -e --source winget --silent --override "--wait --quiet --add ProductLang En-us --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
          winget install --id Python.Python.3.12 -e --source winget

      - name: Build GTK 4
        run: gvsbuild build gtk4

      - name: Build project
        run: |
          $Env:PKG_CONFIG_PATH = "C:\gtk-build\gtk\x64\release\lib\pkgconfig"
          $env:Path = "C:\gtk-build\gtk\x64\release\bin;" + $env:Path
          $env:LIB = "C:\gtk-build\gtk\x64\release\lib;" + $env:LIB
          cargo build --release

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-rust-app-${{ github.sha }}
          path: target/release/game-translator.exe
