name: Rust Build and Release (Windows)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Version
        run: (Get-Content -Path .\Cargo.toml | Select-Object -Index 2) -replace '[^0-9.]' >> $ENV:GITHUB_OUTPUT
        id: version

      - name: Output Version
        run: echo ${{ steps.version.outputs.version }}
